### ISSUE TITLE
Build failed with 1 error

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/rocket-rental#8]
Clean install from github

Windows 11
node: 18.15.0
npm 9.5.0

step to reproduce:
- copy .env.example to .env
- `npm install`
- `npm run setup`
- `npm run dev`

Result:

<details><summary>Build failed with 1 error</summary>

```
 npm run dev

> dev
> cross-env NODE_ENV=development run-p dev:*


> dev:server
> cross-env MOCKS=true tsx watch --clear-screen=false --ignore "app/**" --ignore "build/**" --ignore "node_modules/**" ./index.js


> dev:remix
> cross-env PORT="" remix dev

🔶 Mock server installed
Loading environment variables from .env
🚀  We have liftoff!
Local:            http://localhost:3000
On Your Network:  http://10.100.102.21:3000
Press Ctrl+C to stop

✘ [ERROR] [plugin browser-route-modules] C:\projects\kcd-apps\rocket-rental\app\routes\index.module.css: Unexpected token (1:0)

> 1 | .statsDistance {
    | ^
  2 |   background: linear-gradient(
  3 |           269.6deg,
  4 |           #657cff 13.84%,

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/browserRouteModulesPlugin_v2.js:122:12:
      122 │       build.onLoad({
          ╵             ~~~~~~

    at setup (C:\projects\kcd-apps\rocket-rental\node_modules\@remix-run\dev\dist\compiler\plugins\browserRouteModulesPlugin_v2.js:122:13)
    at handlePlugins (C:\projects\kcd-apps\rocket-rental\node_modules\esbuild\lib\main.js:1276:21)


Build failed with 1 error:
error: C:\projects\kcd-apps\rocket-rental\app\routes\index.module.css: Unexpected token (1:0)

> 1 | .statsDistance {
    | ^
  2 |   background: linear-gradient(
  3 |           269.6deg,
  4 |           #657cff 13.84%,
💿 Built in 3.1s
```
</details>

**Comment by onemen** [comment]
moving `index.module.css` out of `routes` folder fix the issue for me.

maybe something is wrong with `remix.config.js`  ?

**Comment by onemen** [comment]
This issue was fixed by https://github.com/remix-run/remix/pull/6017

**Comment by onemen** [comment]
simple workaround is to move `app/routes/index.module.css` to `app/styles/index.module.css` 
and fix the link in `app/routes/index.tsx` to `import styles from '../styles/index.module.css'`

**Comment by kentcdodds** [comment]
Thanks. I guess I'll do that if we don't get a remix release in time for the workshop

**Comment by kentcdodds** [comment]
This is no longer actively maintained, so I'm closing this issue. If you want an up-to-date example of a Remix app that builds on top of what was done here, check [the Epic Stack](https://github.com/epicweb-dev/epic-stack).
